print("Metu Acm")
print("Git ve Github Eğitimi")
print("Metu ACM'e hoşgeldiniz")
print("Tanışma Standımıza bekliyoruz")
print("Metu ACM Üyelerimize Sevgiler")
print("Yeni hesabımızla commit")
print("Eğitim için teşekkürler!")
